### ISSUE TITLE
ember-cli deprecation warnings

### ISSUE THREAD

**Issue by ianpetzer** [runspired/ember-hammertime#21]
I'm getting the following errors in my ember-cli output

    DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `touch-action`.

    DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `touch-action`.

I chatted to @runspired and this has actually been fixed in develop branch. I can confirm that if I run against the develop branch then the warning dissapears. Just leaving this here to help anyone that might encounter this until a new version is released

**Comment by runspired** [comment]
Going to get a new release out this evening :)

**Comment by ianpetzer** [comment]
Amazing, Thanks!

**Comment by runspired** [comment]
Resolved by the release of 1.1.0
