### ISSUE TITLE
ember-hammertime#develop seems to be removing attributeBindings for components with a specified tag name

### ISSUE THREAD

**Issue by ianpetzer** [runspired/ember-hammertime#22]
Hi,

I've tried running my app agains the latest version of ember-hammertime#develop and I've observed that the attributeBindings are being ignored on my component which specifies a tag name of 'img'. In addition, my checkboxes are rendering as input boxes.

I suspect it might be due to [this](https://github.com/runspired/ember-hammertime/pull/18/commits/d061986d20c2e1bc34aca3c7a4373a25ff095067#diff-758ea84d5cec48637251fcecdd1d536bR13): But thats just speculation

**Comment by wongpeiyi** [comment]
I think this should be fixed by https://github.com/runspired/ember-hammertime/pull/20 (which is merged into latest develop and master)

**Comment by ianpetzer** [comment]
@wongpeiyi I can confirm that this is now fixed on latest develop.. Will close the issue.

Thanks!
