### ISSUE TITLE
Question: Is this a replacement for FastClick?

### ISSUE THREAD

**Issue by alizahid** [runspired/ember-hammertime#6]
If I have this library, can I skip [FastClick](https://github.com/ftlabs/fastclick)? Or do I need that anyway? I'm building Ember apps for mobile.

**Comment by runspired** [comment]
Skip fastclick, this is a replacement.

**Comment by alizahid** [comment]
I'm seeing the 300ms delay on mobile if I package my app through Cordova. Any ideas?

**Comment by runspired** [comment]
@alizahid 

Potential errors
- did you also install FastClick
- are you using wkWebView and iOS 9.3+ and an old version of ember-hammertime?
- what is the viewport meta tag set to?
- did you npm install instead of bower install, and are missing hammer-time?

**Comment by alizahid** [comment]
- did you also install FastClick - **no**
- are you using wkWebView and iOS 9.3+ and an old version of ember-hammertime? - **no**
- what is the viewport meta tag set to? - **`user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width`**
- did you npm install instead of bower install, and are missing hammer-time? - **`ember install ember-hammertime`**

**Comment by alizahid** [comment]
Bump.

**Comment by runspired** [comment]
@alizahid can you detail which platform you are on?

**Comment by alizahid** [comment]
- Ember 2.4.5
- Ember Data 2.5.2
- jQuery 2.2.3
- iOS 9.3.1 (13E238)
- Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13E238 (367551184)
- iPhone 6S
- Cordova 6.1.1
- Cordova iOS 4.1.1

You can see the styles are applied. But it's not working.

<img width="808" alt="screenshot 2016-05-01 19 40 29" src="https://cloud.githubusercontent.com/assets/941775/14941630/9734cc14-0fd4-11e6-96ea-b1385902b74e.png">

I even tried to install `ember-hammertime` again, but no change.

PS: there's no delay if I run the app in Safari on the iPhone. Only when it's packaged through Cordova. Could be a conflict?

**Comment by runspired** [comment]
@arschmitz

**Comment by arschmitz** [comment]
So this seems like an iOS bug thats not properly applying the css. hammer-time is a noop on 9.3 currently and `touch-action: manipulation` is natively supported in iOS 9.3.

@runspired have you seen `touch-action: manipulation` working at all in cordova in 9.3? not sure i have tried it.

**Comment by runspired** [comment]
@arschmitz yes, I'm worried that hammer-time's no-op is doing a bad check, since this appears to be isolated to uiWebView on 9.3

**Comment by runspired** [comment]
@alizahid fwiw I know other teams are using this with cordova and it's working on 9.3 for them.  There's definitely something strange here that you are still seeing a 300ms delay, and after looking at how hammer-time does the `touch-action` support check, I think it's increasingly likely there's something going on in your cordova config.  It's also possible that you are making use of `:hover` classes on these buttons/links?

@arschmitz I don't think this should be no-op for uiWebView on 9.3....
https://github.com/hammerjs/hammer-time/blob/master/hammer-time.js#L17

**Comment by alizahid** [comment]
I have no `:hover` styles, and using the stock Cordova configuration.

If it's a 9.3 bug, do note that the delay isn't there in Safari browser, only in UIWebView.

Just tested it on Android 6, no delay.

**Comment by arschmitz** [comment]
@runspired is right i don't noop in the webview it does not support `touch-action` however not really sure what the issue is. I have not had any other reports of issues in cordova and i know @runspired and others are using it successfully.

**Comment by gnazarkin** [comment]
Having the same problem. @alizahid any solutions you've found?

**Comment by alizahid** [comment]
@gnazarkin No, I still haven't.
